### ISSUE TITLE
Boltz Backend should pay invoice via a specific route if chan_id is specified

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-backend#197]
Letting Boltz construct a route via a specified channel when the channel id is specified would allow for creation of more custom channel opening and normal submarine swaps.

**Comment by armurbalda** [comment]
we'll look into this once there is a need again

**Comment by kilrau** [comment]
To be clear: this is needed for swap INs to come in/rebalance a _specific_ channel

**Comment by kilrau** [comment]
Idea just came up to also let users specify the "to be rebalenced" channel via routing hints in the invoice (even if the channels in the hints are public). With these hints it should be much easier and faster for us to construct the route.

**Comment by TrezorHannes** [comment]
Let's add a CLI or ideally CLI + WebUI to determine the last hop before my node, so I can specify the incoming channel.
This probably requires for boltz-backend to probe the route again after a pubkey is set as last hop, because likely it's either
- a sink node with high cost to route to. Since other boltz channel peers would have exploited this route if it's a low PPM channel for them, you need to consider the lost opportunity costs
- a node where there is no direct channel b/w Boltz and the target incoming channel for the swapper. This would require Boltz-backend to check for possible routes, peer channel fees incurring and available liquidity

So to allow a profitable, fair and transparent process, it would require to add the incurring costs to the swap fee. Otherwise there is a risk of an exploit. For example, I could determine fixedfloat as incoming channel, 99% of liquidity is on their side. Boltz would need to route via them, which likely is a 3000ppm endevour.

**Comment by kilrau** [comment]
Bumping prio here, as now this is becoming relevant for Boltz Pro
