### ISSUE TITLE
WebHook calls for swap update events

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-backend#605]
The backend should allow setting a WebHook URL when swaps are created. That WebHook should be called on every swap status update.

I am not yet sure about:
- what data should be sent to the WebHook
- what format the data sent should have
- if the client should be allowed to specify for which events the WebHook is called
- alias swap ids in case the WebHook is handled by a 3rd party

**Comment by roeierez** [comment]
I see webhooks as a way to notify clients for action item. 
For example 
On receiving - a mobile application can receive offline by using a webhook to get notified for a specific swap that is ready to be claimed, the apps wake up and claims.
On Sending - a mobile application can use webhook to get notified when boltz need it for cooperative claim, app wakes up and cooperate with the claim.

Since webhooks can not hit directly the mobile device (which expects a push notification) there will always be a middleware service that receives the webhook and translate that into a push notification and because of that it would be nice to come up with a mechanism where payload that is sent doesn't expose any information about the transaction.

Suggestion:

On create swap two fields are added to the request payload:
1. Webhook URL - the url to invoke when the swap status changes
2. Webhook Swap ID - the identifier of the swap that is used in the web hook payload. This id can not lead to the swap details by a third party.

When the status changes, boltz invoke a POST request to the webhook with the following payload:
```
{
"event": "swap.update"
  "data": {
   "webhook_swap_id": <user provided id>
   "status": <new swap status>
  }
}
```

**Comment by michael1011** [comment]
> the identifier of the swap that is used in the web hook payload. This id can not lead to the swap details by a third party.

I am super paranoid about data coming from the client. And when you let the client provide an id and it happens to be a duplicate you have to throw an error `swap id alias already used`. Unlikely but possible.

What we can do is allow the client to specify something like this in the request:

```json
{
  ...
  "websocket": {
    "url": "<some url>",
    "aliasSwapId": true
  }
}
```

And in the response they get a second swap id that is used in the WebHook. Same end result but easier for the backend side.

**Comment by michael1011** [comment]
Another option would be to hash the swap id in the data sent to the WebSocket. Would save ourselves having to handle an alias
